kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress
  labels:
    k8s-app: traefik-ingress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    k8s-app: traefik-ingress
  ports:
  - protocol: TCP
    port: 80
    name: web
  - protocol: TCP
    port: 8080
    name: admin
  type: LoadBalancer