kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress
  labels:
    k8s-app: traefik-ingress
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
        name: traefik-ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 60
      containers:
        - name: traefik-ingress
          image: traefik:v1.7.12
          resources:
            limits:
              cpu: 0.2
              memory: 200M
            requests:
              cpu: 0.2
              memory: 200M
          ports:
            - name: http
              hostPort: 32788
              containerPort: 80
            - name: admin
              hostPort: 32789
              containerPort: 8080
          args:
            - --api
            - --kubernetes
            - --logLevel=FATAL
            - --metrics.prometheus
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
            timeoutSeconds: 10