apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    app: mosquitto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: toke/mosquitto
        name: mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mqtt/data
          name: mosquitto-data
      restartPolicy: Always
      volumes:
      - name: mosquitto-data
        emptyDir: {}